package parentsgui;

import authorization.Auth;
import javax.swing.table.DefaultTableModel;
import miscgui.MainGUI;
import miscgui.Results;
import users.Parent;
import users.Student;

/**
 * This is the class for the Parent GUI.
 * @author William Pruitt Final Project
 */
public class ParentGUI extends javax.swing.JFrame {

    Parent currentParent = (Parent) Auth.hello;

    /**
     * Creates new form ParentGUI
     */
    public ParentGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        youChildGradesButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        parentChildrenList = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math is FUN");

        youChildGradesButton.setBackground(new java.awt.Color(0, 0, 255));
        youChildGradesButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        youChildGradesButton.setForeground(new java.awt.Color(255, 255, 255));
        youChildGradesButton.setText("Your Child's Grades");
        youChildGradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youChildGradesButtonActionPerformed(evt);
            }
        });

        backButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        parentChildrenList.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        parentChildrenList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {"Select a Child."})

        );
        parentChildrenList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parentChildrenListActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(youChildGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(187, 187, 187))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(parentChildrenList, javax.swing.GroupLayout.PREFERRED_SIZE, 244, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addComponent(parentChildrenList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addComponent(youChildGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );

        String childName;
        for (int i = 0; i < currentParent.getChildList().size(); i++) {
            childName = currentParent.getChildList().get(i).getFirst();
            parentChildrenList.addItem(childName);
        }
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Please Select From The Following Options");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 750, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        MainGUI mGUI = new MainGUI();
        mGUI.setVisible(true);
        mGUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_backButtonActionPerformed

    private void parentChildrenListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parentChildrenListActionPerformed

    }//GEN-LAST:event_parentChildrenListActionPerformed

    private void youChildGradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youChildGradesButtonActionPerformed

        String chosen = (String) parentChildrenList.getSelectedItem();
        Results res = new Results();
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) res.jTable1.getModel();
        int num = 1;

        for (int i = 0; i < currentParent.getChildList().size(); i++) {
            if (currentParent.getChildList().get(i).getFirst().equals(chosen)) {
                Student parentStudent = (Student) currentParent.getChildList().get(i);
                Object[] newRow = {parentStudent.getFirst() + " " + parentStudent.getLast(),
                     parentStudent.getGradeLevel() , parentStudent.getAverageGrade()};
               

                model.addRow(newRow);

                for (int ly = 0; ly < parentStudent.getGradeList().size() - 1; ly++) {
                    Object[] new2Row = {"Quizes: " + num++, parentStudent.getGradeList().get(ly)};
                    

                    model.addRow(new2Row);

                }
                Object[] new3Row = {"", "",};
                model.addRow(new3Row);
            }

        }

    }//GEN-LAST:event_youChildGradesButtonActionPerformed

    private void updateList() {

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ParentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ParentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ParentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ParentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ParentGUI pGUI = new ParentGUI();
                pGUI.setVisible(true);
                pGUI.setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> parentChildrenList;
    private javax.swing.JButton youChildGradesButton;
    // End of variables declaration//GEN-END:variables
}
