package studentgui;

import authorization.Auth;
import javax.swing.table.DefaultTableModel;
import miscgui.MainGUI;
import miscgui.Results;
import quizgui.*;
import users.Student;
import static users.Student.currentStudent;

/**
 * The opening menu for the student login.
 * @author William Pruitt
 */
public class StudentGUI extends javax.swing.JFrame {

    /**
     * Creates new form StudentGUI
     */
    public StudentGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        takePracticeButton = new javax.swing.JButton();
        getMyGradesButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gradeLevel = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math is Fun");

        takePracticeButton.setBackground(new java.awt.Color(0, 0, 255));
        takePracticeButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        takePracticeButton.setForeground(new java.awt.Color(255, 255, 255));
        takePracticeButton.setText("Take Practice Test");
        takePracticeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takePracticeButtonActionPerformed(evt);
            }
        });

        getMyGradesButton.setBackground(new java.awt.Color(0, 0, 255));
        getMyGradesButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        getMyGradesButton.setForeground(new java.awt.Color(255, 255, 255));
        getMyGradesButton.setText("Get Grades");
        getMyGradesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getMyGradesButtonActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel2.setText("Please Select From The Following Options");

        backButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Select Grade Level:");

        gradeLevel.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        gradeLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeLevelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(72, 72, 72)
                        .addComponent(gradeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(getMyGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(takePracticeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(50, 50, 50))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(takePracticeButton, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                            .addComponent(gradeLevel))))
                .addGap(18, 18, 18)
                .addComponent(getMyGradesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        MainGUI mGUI = new MainGUI();
        mGUI.setVisible(true);
        mGUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_backButtonActionPerformed

    private void takePracticeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takePracticeButtonActionPerformed
        dispose();
        String gradeLe = gradeLevel.getText();

        switch (gradeLe) {
            case "1":
                FirstGradeTestSelector stuTest = new FirstGradeTestSelector();
                stuTest.setVisible(true);
                stuTest.setLocationRelativeTo(null);
                break;
            case "2":
                SecondGradeTestSelector stu2Test = new SecondGradeTestSelector();
                stu2Test.setVisible(true);
                stu2Test.setLocationRelativeTo(null);
                break;
            case "3":
                ThirdGradeTestSelector stu3Test = new ThirdGradeTestSelector();
                stu3Test.setVisible(true);
                stu3Test.setLocationRelativeTo(null);
                break;
            case "4":
                FourthGradeTestSelector stu4Test = new FourthGradeTestSelector();
                stu4Test.setVisible(true);
                stu4Test.setLocationRelativeTo(null);
                break;
            case "5":
                FifthGradeTestSelector stu5Test = new FifthGradeTestSelector();
                stu5Test.setVisible(true);
                stu5Test.setLocationRelativeTo(null);
                break;

            default:
                StudentGUI remake = new StudentGUI();
                remake.setVisible(true);
                remake.setLocationRelativeTo(null);

                System.out.println("not right");
                System.out.println(gradeLe);
        }

    }//GEN-LAST:event_takePracticeButtonActionPerformed

    private void gradeLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeLevelActionPerformed

    private void getMyGradesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getMyGradesButtonActionPerformed

        Results res = new Results();
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) res.jTable1.getModel();
        Object[] newRow = {currentStudent.getFirst() + " " + currentStudent.getLast(), currentStudent.getGradeLevel()};

        model.addRow(newRow);

        for (int i = 0; i < currentStudent.getGradeList().size() - 1 ; i++) {
            Object[] new2Row = {"", "" , currentStudent.getGradeList().get(i)};

            model.addRow(new2Row);

        }
        Object[] new3Row = {"", "", ""};
        model.addRow(new3Row);
        Object[] new4Row = {"", "Grade Avrage: ", currentStudent.getAverageGrade()};
        model.addRow(new4Row);


    }//GEN-LAST:event_getMyGradesButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {
        Student.setCurrentStudent((Student) Auth.hello);
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(StudentGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                StudentGUI sGUI = new StudentGUI();
                sGUI.setVisible(true);
                sGUI.setLocationRelativeTo(null);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton getMyGradesButton;
    private javax.swing.JTextField gradeLevel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton takePracticeButton;
    // End of variables declaration//GEN-END:variables
}
