package teachergui;

import authorization.Auth;
import fileParse.ReWrite;
import java.io.File;
import java.io.IOException;
import javax.swing.table.DefaultTableModel;
import miscgui.MainGUI;
import miscgui.Results;
import users.ReadDatabase;
import users.Teacher;

/**
 * Main GUI for teacher use.
 * @author William Pruitt Final Project
 */
public class TeacherGUI extends javax.swing.JFrame {

    /**
     * Creates new form TeacherGUI
     */
    public Teacher currentTeacher = (Teacher) Auth.hello;

    public TeacherGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        numberofStudents = new javax.swing.JTextField();
        listStudents = new javax.swing.JButton();
        searchStudents = new javax.swing.JButton();
        sortStudents = new javax.swing.JButton();
        updateButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Math is Fun");

        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jLabel1.setText("Please Select From The Following Options");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Enter The number Of Students:");

        numberofStudents.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        numberofStudents.setText(String.valueOf(currentTeacher.getClassSize()));
        numberofStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                numberofStudentsActionPerformed(evt);
            }
        });

        listStudents.setBackground(new java.awt.Color(0, 0, 255));
        listStudents.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        listStudents.setForeground(new java.awt.Color(255, 255, 255));
        listStudents.setText("List Students");
        listStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listStudentsActionPerformed(evt);
            }
        });

        searchStudents.setBackground(new java.awt.Color(0, 0, 255));
        searchStudents.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        searchStudents.setForeground(new java.awt.Color(255, 255, 255));
        searchStudents.setText("Search Students");
        searchStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchStudentsActionPerformed(evt);
            }
        });

        sortStudents.setBackground(new java.awt.Color(0, 0, 255));
        sortStudents.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        sortStudents.setForeground(new java.awt.Color(255, 255, 255));
        sortStudents.setText("Sort Students");
        sortStudents.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortStudentsActionPerformed(evt);
            }
        });

        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(157, 157, 157)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(searchStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sortStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(listStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(numberofStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(73, 73, 73)
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(updateButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(numberofStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(41, 41, 41)
                        .addComponent(listStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sortStudents, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(77, 77, 77))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void sortStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortStudentsActionPerformed
        // TODO add your handling code here:
        dispose();
        SortGUI sGUI = new SortGUI();
        sGUI.setVisible(true);
        sGUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_sortStudentsActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        dispose();
        MainGUI mGUI = new MainGUI();
        mGUI.setVisible(true);
        mGUI.setLocationRelativeTo(null);
    }//GEN-LAST:event_backButtonActionPerformed

    private void searchStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchStudentsActionPerformed
        // TODO add your handling code here:
        dispose();
        SearchGUI sGUI = new SearchGUI();
        sGUI.setVisible(true);
        sGUI.setLocationRelativeTo(null);

    }//GEN-LAST:event_searchStudentsActionPerformed

    private void listStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listStudentsActionPerformed

        try {
            ReadDatabase.ScanDatabase();
        } catch (IOException ex) {
            System.out.println("There was an error scanning the DATABASE");
        }
        Results res = new Results();
        res.setVisible(true);
        res.setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) res.jTable1.getModel();
        int num = Integer.parseInt(numberofStudents.getText());
        int newNum = 2;
        for (int i = 0; i < num - 1; i++) {
            if (i < currentTeacher.students.size()) {
                Object[] newRow = {currentTeacher.students.get(i).getFirst() + " "
                    + currentTeacher.students.get(i).getLast(),
                    currentTeacher.students.get(i).getGradeLevel(),
                    currentTeacher.students.get(i).getAverageGrade()};
                model.addRow(newRow);
                newNum++;
            } else {

                Object[] new2Row = {newNum, null, null};

                model.addRow(new2Row);
                newNum++;
            }
        }


    }//GEN-LAST:event_listStudentsActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        try {
            ReWrite.classSizeRewrite(new File(currentTeacher.getFirst()
                    + currentTeacher.getLast() + ".txt"),
                    Integer.valueOf(numberofStudents.getText()));
            currentTeacher.classSize = Integer.valueOf(numberofStudents.getText());
        } catch (Exception ex) {
            System.out.println("A problem has occurred");
        }

    }//GEN-LAST:event_updateButtonActionPerformed

    private void numberofStudentsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_numberofStudentsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_numberofStudentsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args) {

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TeacherGUI tGUI = new TeacherGUI();
                tGUI.setVisible(true);
                tGUI.setLocationRelativeTo(null);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton listStudents;
    private javax.swing.JTextField numberofStudents;
    private javax.swing.JButton searchStudents;
    private javax.swing.JButton sortStudents;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
